// Generated by CoffeeScript 1.9.3

/* 服务端入口文件 */
var cache, chat, fs, http, mime, path, send404, sendFile, serveStatic, server;

http = require('http');

path = require('path');

mime = require('mime');

fs = require('fs');

chat = require('./lib/server_chat');

cache = {};


/* 全局 http 请求文件不存在 发送404 */

send404 = function(response) {
  response.writeHead(404, {
    'Content-Type': 'text/plain'
  });
  response.write('Error 404: Page not found!!!!!!!!!!!');
  return response.end();
};


/* 发送文件内部的数据 */

sendFile = function(response, filepath, fileContent) {
  response.writeHead(200, {
    'Content-Type': mime.lookup(path.basename(filepath))
  });
  response.end(fileContent);
  return chat.listen(server);
};


/* 提供静态文件服务 */

serveStatic = function(response, cache, absPath) {
  if (cache[absPath]) {
    return response.write('有缓存');
  } else {
    return fs.exists(absPath, function(exists) {
      if (exists) {
        return fs.readFile(absPath, function(err, data) {
          if (err) {
            return send404(response);
          } else {
            cache[absPath] = data;
            return sendFile(response, absPath, data);
          }
        });
      } else {
        return send404(response);
      }
    });
  }
};


/*  创建一个http服务器和启动服务器 */

server = http.createServer(function(request, response) {
  var absPath, filepath;
  filepath = false;
  if (request.url === '/') {
    filepath = 'publish/index.html';
  } else {
    filepath = 'publish' + request.url;
  }
  absPath = './' + filepath;

  /*  响应请求 */
  return serveStatic(response, cache, absPath);
});

server.listen(8888);
