// Generated by CoffeeScript 1.9.3

/* ... */
var chat;

chat = {
  ws: io.connect('http://127.0.0.1:8888'),

  /* 绑定客户端监听 */
  init: function() {
    var _self;
    _self = this;
    return _self.bind();
  },
  sendMessage: function(message) {
    return ws.emit('send', message);
  },
  bind: function() {
    return $(document).on('click', '#send-btn', function() {});
  }
};

chat.init();
