// Generated by CoffeeScript 1.9.3

/*　聊天的方法 */
var chat;

chat = function(server) {

  /* 引入socket.io模块 */
  var currentRoom, guestNumber, io, nameused, socketio;
  socketio = require('socket.io');

  /*  定义聊天的一些变量 */
  nameused = [];
  currentRoom = {};
  guestNumber = 1;
  io = socketio.listen(server);
  return io.sockets.on('connection', function(socket) {
    return socket.on('send', function(msg) {
      return socket.emit('get', msg);
    });
  });
};

exports.listen = chat;
