// Generated by CoffeeScript 1.9.3

/* 引入socket.io模块 */
var currentRoom, guestNumber, nameused, socketio;

socketio = require('socket.io');


/*  定义聊天的一些变量 */

io;

nameused = [];

currentRoom = {};

guestNumber = 1;

exports.listen = function(server) {

  /* 把io绑定到http服务器上 */
  this.io = socketio.listen(server);

  /* */
  return io.sockets.on('connection', function(socket) {
    return console.log(socket);
  });
};
